import React from "react";

export function PrintView({ trip }) {
  if (!trip) return null;

  const hotels = trip.places?.filter((p) => p.category === "hotels") || [];
  const emergencyContacts = trip.tips?.emergencyContacts || [];
  const currencySymbol = trip.currencySymbol || "€";

  return (
    <div className="print-only p-8 text-black bg-white max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="border-b-2 border-black pb-4 flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            {trip.destination}
          </h1>
          <p className="text-base text-gray-700 font-medium mt-1">{trip.subtitle}</p>
          <div className="text-sm text-gray-600 mt-2">
            <span><strong>Dates:</strong> {trip.dateRange} ({trip.durationDays} Days)</span>
          </div>
        </div>
        <div className="text-right text-sm">
          <div className="font-bold">OFFICIAL TRIP ITINERARY</div>
          <div className="text-gray-500 text-xs">Generated by Travel Planner</div>
          <div className="mt-2 text-xs text-gray-600">
            <strong>Travelers:</strong>{" "}
            {trip.companions?.map((c) => `${c.name} (${c.role})`).join(", ")}
          </div>
        </div>
      </div>

      {/* Accommodations Box */}
      {hotels.length > 0 && (
        <div className="print-break-inside-avoid">
          <h2 className="text-lg font-bold uppercase tracking-wider mb-2 border-b border-gray-300 pb-1">
            Accommodations & Lodging
          </h2>
          <table className="w-full text-xs text-left border border-gray-300">
            <thead className="bg-gray-100">
              <tr>
                <th className="p-2 border border-gray-300">Hotel / Stay</th>
                <th className="p-2 border border-gray-300">Address / Location</th>
                <th className="p-2 border border-gray-300">Check-in / Out</th>
                <th className="p-2 border border-gray-300">Notes / Confirmation</th>
              </tr>
            </thead>
            <tbody>
              {hotels.map((h) => (
                <tr key={h.id}>
                  <td className="p-2 border border-gray-300 font-bold">{h.name}</td>
                  <td className="p-2 border border-gray-300">{h.location}</td>
                  <td className="p-2 border border-gray-300">
                    In: {h.checkIn || "15:00"} · Out: {h.checkOut || "11:00"}
                  </td>
                  <td className="p-2 border border-gray-300 text-gray-700">{h.notes || "--"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Day-by-Day Schedule */}
      <div className="print-break-inside-avoid">
        <h2 className="text-lg font-bold uppercase tracking-wider mb-2 border-b border-gray-300 pb-1">
          Day-by-Day Itinerary Schedule
        </h2>
        <table className="w-full text-xs text-left border border-gray-300">
          <thead className="bg-gray-100">
            <tr>
              <th className="p-2 border border-gray-300 w-24">Day</th>
              <th className="p-2 border border-gray-300 w-24">Period / Time</th>
              <th className="p-2 border border-gray-300">Activity / Place</th>
              <th className="p-2 border border-gray-300">Location</th>
              <th className="p-2 border border-gray-300 w-24">Status / Cost</th>
              <th className="p-2 border border-gray-300">Reminders / Details</th>
            </tr>
          </thead>
          <tbody>
            {trip.itinerary?.map((item) => (
              <tr key={item.id} className={item.completed ? "bg-gray-50" : ""}>
                <td className="p-2 border border-gray-300 font-bold">
                  {item.dayLabel || `Day ${item.dayNumber}`}
                </td>
                <td className="p-2 border border-gray-300">
                  <div className="font-semibold">{item.period}</div>
                  <div className="text-[10px] text-gray-500">{item.time}</div>
                </td>
                <td className="p-2 border border-gray-300 font-bold">{item.activity}</td>
                <td className="p-2 border border-gray-300">{item.location || "--"}</td>
                <td className="p-2 border border-gray-300">
                  <div>{item.bookingStatus || "--"}</div>
                  {item.cost > 0 && (
                    <div className="font-bold">{currencySymbol}{item.cost}</div>
                  )}
                </td>
                <td className="p-2 border border-gray-300 text-gray-700">{item.notes || "--"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Emergency Contacts & Key Logistics */}
      {emergencyContacts.length > 0 && (
        <div className="print-break-inside-avoid pt-2">
          <h2 className="text-base font-bold uppercase tracking-wider mb-2 border-b border-gray-300 pb-1">
            Emergency Contacts
          </h2>
          <div className="grid grid-cols-2 gap-2 text-xs">
            {emergencyContacts.map((c, idx) => (
              <div key={idx} className="border border-gray-200 p-2 rounded">
                <span className="font-bold">{c.name}:</span> <span>{c.number}</span> ({c.desc})
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
        Printed on {new Date().toLocaleDateString()} · Have a wonderful trip to {trip.destination}!
      </div>
    </div>
  );
}
